language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2.3
  - 2.3.1
  - ruby-head

script:
  - chmod a+x ci/travis.sh
  - sh ci/travis.sh

bundler_args: --without development

matrix:
  allow_failures:
    - rvm: ruby-head
