language: ruby
cache: bundler
sudo: false

rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.4

bundler_args: --without development

services:
  - postgresql

addons:
  postgresql: "9.4"

matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - psql -c 'create database sample_test;' -U postgres

script:
  - chmod a+x ci/travis.sh
  - sh ci/travis.sh